options(shiny.maxRequestSize = 1000 * 1024^2)

library(shiny)
library(shinyjs)
library(dplyr)
library(purrr)
library(stringr)
library(DT)
library(tibble)
library(httr2)
library(metacheck)
library(digest)
library(htmltools)

source("../R/utils.R")
source("../R/taxonomy.R")
source("../R/db.R")
source("../R/extraction.R")
source("../R/llm.R")
source("../R/llm_html.R")
source("../R/analyzer_api.R")
